#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l ncpus=1
#PBS -l mem=60gb
#PBS -l walltime=24:00:00

# Header
DATADIRECTORY=/home/ref-bioinfo/ifremer/rmpf/Pmarg_color_WGS_2018/data/dna-sequence-raw
DATAOUTPUT=/home1/datahome/plstenge/Pearl_Oyster_Colour_Population_Genomics/03_trimmed
SCRIPT=$0
HEADER=/home1/datahome/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/header.txt
TRIMMOMATICENV=". /appli/bioinfo/trimmomatic/latest/env.sh"
TIMESTAMP=$(date +%Y-%m-%d_%Hh%Mm%Ss)
LOG_FOLDER=/home1/datahome/plstenge/Pearl_Oyster_Colour_Population_Genomics/98_log_files
NAME=$(basename $0)


# Global variables

#>Illumina_TruSeq_LT_R1 AGATCGGAAGAGCACACGTCTGAACTCCAGTCAC
#>Illumina_TruSeq_LT_R2 AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT
ADAPTERFILE=/home1/datahome/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/adapters.fasta
NCPU=8
base=*

$TRIMMOMATICENV

cp $SCRIPT $LOG_FOLDER/"$TIMESTAMP"_"$NAME"

for file in $(ls $DATADIRECTORY/*.fastq.gz) :
do

trimmomatic PE -Xmx60G \
        -threads 8 \
        -phred33 \
        $DATADIRECTORY/*R1.fastq.gz \
        $DATADIRECTORY/*R2.fastq.gz \
        $DATAOUTPUT/*R1.paired.fastq.gz \
        $DATAOUTPUT/*R1.single.fastq.gz \
        $DATAOUTPUT/*R2.paired.fastq.gz \
        $DATAOUTPUT/*R2.single.fastq.gz \
        ILLUMINACLIP:"$ADAPTERFILE":2:30:10 \
        LEADING:28 \
        TRAILING:28 \
        SLIDINGWINDOW:4:28 \
        MINLEN:40 2> $LOG_FOLDER/log.trimmomatic.pe."$TIMESTAMP"
	
done	
	
