#!/usr/bin/env bash
#PBS -o flagstat.out
#PBS -q omp
#PBS -l ncpus=8
#PBS -l mem=60gb
#PBS -l walltime=96:00:00
#PBS -r n

# Header
DATADIRECTORY=/home1/scratch/plstenge/testBWA/mapping_BWA_sspace.final.scaffolds.fasta
DATAOUTPUT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/06_flagstat
SCRIPT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/06_flagstat.qsub
HEADER=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/header.txt
FLAGSTATENV=". /appli/bioinfo/samtools/latest/env.sh"


cd $PBS_O_WORKDIR


for i in *.bam; do
    samtools view $i | cut -f1 | sort | uniq | wc -l >> $DATAOUTPUT
done
