#!/usr/bin/env bash
#PBS -q mpi
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=28:mem=115g

WORKING_DIRECTORY=/home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta
SCRIPT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts
SAMTOOLS="samtools"
SAM_ENV=". /appli/bioinfo/samtools/latest/env.sh"
NB_CPU=16	#number of cpus

$SAM_ENV
cd $WORKING_DIRECTORY
samtools view -b HI.4506.005.NS_Adaptor_9.pool1TR_05_mapping_unique_sequentiel.sam > HI.4506.005.NS_Adaptor_9.pool1TR_05_mapping_unique_sequentiel.bam
