
#!/usr/bin/env bash
#PBS -o Sam_to_Bam.out
#PBS -q omp
#PBS -l ncpus=16
#PBS -l mem=60gb
#PBS -l walltime=96:00:00
#Global variables

WORKING_DIRECTORY=/home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta
SCRIPT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts
SAMTOOLS="samtools"
SAM_ENV=". /appli/bioinfo/samtools/latest/env.sh"
NB_CPU=16	#number of cpus

$SAM_ENV
cd $WORKING_DIRECTORY
samtools view -b HI.4506.004.NS_Adaptor_10.pool2TJ_05_mapping_unique_sequentiel.sam > HI.4506.004.NS_Adaptor_10.pool2TJ_05_mapping_unique_sequentiel.bam
