#!/usr/bin/env bash
#PBS -o Sam_to_Bam.out
#PBS -q omp
#PBS -l ncpus=16
#PBS -l mem=60gb
#PBS -l walltime=96:00:00
#Global variables

WORKING_DIRECTORY=/home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
SCRIPT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts
SAMTOOLS="samtools"
SAM_ENV=". /appli/bioinfo/samtools/latest/env.sh"
NB_CPU=16	#number of cpus

$SAM_ENV
cd $WORKING_DIRECTORY
samtools view -b HI.4527.005.NS_Adaptor_19.pool11EJ_05_mapping_unique_sequentiel.sam > HI.4527.005.NS_Adaptor_19.pool11EJ_05_mapping_unique_sequentiel.bam
