#!/usr/bin/env bash
#PBS -o flagstat.out
#PBS -q omp
#PBS -l ncpus=16
#PBS -l mem=60gb
#PBS -l walltime=96:00:00
#Global variables

ASSEMBLY=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/01_data/sspace.final.scaffolds.fasta
INPUT=/home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta/HI.4499.007.NS_Adaptor_15.pool7KR.sam
WORKING_DIRECTORY=/home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta
SCRIPT=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts
HEADER=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/header.txt
SAMTOOLS="samtools"
SAM_ENV=". /appli/bioinfo/samtools/latest/env.sh"
NB_CPU=16	#number of cpus

$SAM_ENV
cd $WORKING_DIRECTORY
samtools view -b HI.4506.002.NS_Adaptor_12.pool4GR.sam  >  HI.4506.002.NS_Adaptor_12.pool4GR.bam
samtools view -b HI.4506.003.NS_Adaptor_11.pool3TV.sam  >  HI.4506.003.NS_Adaptor_11.pool3TV.bam
