#!/usr/bin/env bash
#PBS -q mpi
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=28:mem=115g

DATAWORK=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/07_01_vcf_files_modified

cd $DATAWORK

# Cat all problematics scaffold to find them and rerun the glm

cat input_glm_split_with_iteration_results_00_not_ok.txt input_glm_split_with_iteration_results_02_not_ok.txt input_glm_split_with_iteration_results_03_not_ok.txt input_glm_split_with_iteration_results_11_not_ok.txt input_glm_split_with_iteration_results_12_not_ok.txt input_glm_split_with_iteration_results_13_not_ok.txt input_glm_split_with_iteration_results_14_not_ok.txt input_glm_split_with_iteration_results_15_not_ok.txt input_glm_split_with_iteration_results_16_not_ok.txt input_glm_split_with_iteration_results_17_not_ok.txt input_glm_split_with_iteration_results_18_not_ok.txt input_glm_split_with_iteration_results_19_not_ok.txt input_glm_split_with_iteration_results_20_not_ok.txt input_glm_split_with_iteration_results_21_not_ok.txt input_glm_split_with_iteration_results_22_not_ok.txt input_glm_split_with_iteration_results_23_not_ok.txt input_glm_split_with_iteration_results_24_not_ok.txt input_glm_split_with_iteration_results_25_not_ok.txt input_glm_split_with_iteration_results_26_not_ok.txt > input_glm_split_with_iteration_results_00_2_3_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_not_ok.txt 


cat input_glm_split_with_iteration_00 input_glm_split_with_iteration_01 input_glm_split_with_iteration_02 input_glm_split_with_iteration_03 input_glm_split_with_iteration_04 input_glm_split_with_iteration_05 input_glm_split_with_iteration_06 input_glm_split_with_iteration_07 input_glm_split_with_iteration_08 input_glm_split_with_iteration_09 input_glm_split_with_iteration_10 input_glm_split_with_iteration_11 input_glm_split_with_iteration_12 input_glm_split_with_iteration_13 input_glm_split_with_iteration_14 input_glm_split_with_iteration_15 input_glm_split_with_iteration_16 input_glm_split_with_iteration_17 input_glm_split_with_iteration_18 input_glm_split_with_iteration_19 input_glm_split_with_iteration_20 input_glm_split_with_iteration_21 input_glm_split_with_iteration_22 input_glm_split_with_iteration_23 input_glm_split_with_iteration_24 input_glm_split_with_iteration_25 input_glm_split_with_iteration_26 input_glm_split_with_iteration_27 input_glm_split_with_iteration_28 input_glm_split_with_iteration_29 > input_glm_split_with_iteration_all
