#!/usr/bin/env bash
#PBS -q mpi
#PBS -l walltime=48:00:00
#PBS -l select=1:ncpus=28:mem=115g

DATAWORK=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/07_01_vcf_files_modified

cd $DATAWORK

# Cat all problematics scaffold to find them and rerun the glm

cat input_glm_split_with_iteration_results_00_not_ok.txt input_glm_split_with_iteration_results_02_not_ok.txt input_glm_split_with_iteration_results_03_not_ok.txt input_glm_split_with_iteration_results_11_not_ok.txt input_glm_split_with_iteration_results_12_not_ok.txt input_glm_split_with_iteration_results_13_not_ok.txt input_glm_split_with_iteration_results_14_not_ok.txt input_glm_split_with_iteration_results_15_not_ok.txt input_glm_split_with_iteration_results_16_not_ok.txt input_glm_split_with_iteration_results_17_not_ok.txt input_glm_split_with_iteration_results_18_not_ok.txt input_glm_split_with_iteration_results_19_not_ok.txt input_glm_split_with_iteration_results_20_not_ok.txt input_glm_split_with_iteration_results_21_not_ok.txt input_glm_split_with_iteration_results_22_not_ok.txt input_glm_split_with_iteration_results_23_not_ok.txt input_glm_split_with_iteration_results_24_not_ok.txt input_glm_split_with_iteration_results_25_not_ok.txt input_glm_split_with_iteration_results_26_not_ok.txt > input_glm_split_with_iteration_results_00_2_3_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_not_ok.txt 
