#!/bin/bash
#PBS -q omp
#PBS -l walltime=180:00:00
#PBS -l mem=1024g
#PBS -l ncpus=12

cd $PBS_O_WORKDIR

#Chargement de conda
export PATH=$PATH:/appli/anaconda/2.7/bin

#Chargement de votre environnement
source activate /home1/datawork/plstenge/96_env_conda/glm

SCRIPT_WGCNA=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/17_00_glm_Tuckey.R

Rscript --vanilla $SCRIPT_WGCNA
