#!/usr/bin/env bash
#PBS -q omp
#PBS -l walltime=180:00:00
#PBS -l mem=120g
#PBS -l ncpus=12
# Mapping BWA
. /appli/bioinfo/bwa/latest/env.sh
time bwa mem -t 12 -M /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/01_data/sspace.final.scaffolds.fasta /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/03_trimmed/HI.4527.006.NS_Adaptor_18.pool10ER_R1.paired.fastq.gz /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/03_trimmed/HI.4527.006.NS_Adaptor_18.pool10ER_R2.paired.fastq.gz > /home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta/HI.4527.006.NS_Adaptor_18.pool10ER.sam
# Sam To Bam
. /appli/bioinfo/samtools/latest/env.sh
samtools view -b  /home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta/HI.4527.006.NS_Adaptor_18.pool10ER.sam  >  /home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta/HI.4527.006.NS_Adaptor_18.pool10ER.bam
# Copy bam file from scratch to datawork_rmpf
cp /home1/scratch/plstenge/BWA/mapping_BWA_sspace.final.scaffolds.fasta/HI.4527.006.NS_Adaptor_18.pool10ER.bam /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
# Flagstat
cd /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
. /appli/bioinfo/samtools/latest/env.sh
samtools flagstat /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER.bam > /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_flagstat_bam.txt
# Filtering
cd /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
. /appli/bioinfo/samtools/latest/env.sh
samtools view -F 4 -F 256 -q 5 -f2 -b /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER.bam > /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered.bam
# Flagstat for filtered files
cd /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
. /appli/bioinfo/samtools/latest/env.sh
samtools flagstat /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered.bam > /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered_flagstat.txt
# Sorting
cd /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
. /appli/bioinfo/samtools/latest/env.sh
samtools sort /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered.bam > /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered_sorted.bam
# Flagstat for sort files
cd /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped
. /appli/bioinfo/samtools/latest/env.sh
samtools flagstat /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered.bam > /home/datawork-rmpf/p_margaritifera/pl-pwgs/03_mapped/HI.4527.006.NS_Adaptor_18.pool10ER_filtered_sorted_flagstat.txt
