#!/bin/bash
#PBS -q omp
#PBS -l walltime=24:00:00
#PBS -l mem=2500g
#PBS -l ncpus=120

cd $PBS_O_WORKDIR

#Chargement de conda
export PATH=$PATH:/appli/anaconda/2.7/bin

#Chargement de votre environnement
source activate /home1/datawork/plstenge/96_env_conda/wgcna

SCRIPT_WGCNA=/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/zw_WGCNArnaSeq.R

Rscript --vanilla $SCRIPT_WGCNA
#Rscript --vanilla /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/00_scripts/zw_WGCNArnaSeq.R
