#!/usr/bin/env bash
#PBS -q mpi
#PBS -l select=1:ncpus=28:mpiprocs=28:mem=60gb
#PBS -l walltime=48:00:00


cp /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/97_tests/

# Activation de l'environnement BLAST+ 2.6.0
. /appli/bioinfo/blast/2.6.0/env.sh

makeblastdb -in /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/97_tests/Transcriptome41K_Trinity_fasta.txt -parse_seqids -dbtype nucl
