#!/usr/bin/env Rscript


#######################################################################################################################
# Set Working Directory
#######################################################################################################################

setwd("/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/08_02_input_pvalued_without_iteration")

#######################################################################################################################
# Import data
#######################################################################################################################

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_000000001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_000000001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_000000001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_000000001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_000000001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier, KatiuVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("YellowVsGreen, YellowVsRed	:", res))

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_000001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_000001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_000001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_000001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_000001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier, KatiuVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("YellowVsGreen, YellowVsRed	:", res))

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier, KatiuVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("YellowVsGreen, YellowVsRed	:", res))

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_01.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_01.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_01.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_01.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_01")
print("#######################################################")

commun<-intersect(HatcheryVsGambier, KatiuVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier, KatiuVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery, RedVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen, TakapotoVsGambier)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsHatchery)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery, TakapotoVsKatiu)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsGreen)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen, YellowVsRed)
res <- length(commun$RedVsGreen)
print(paste0("YellowVsGreen, YellowVsRed	:", res))
