#!/usr/bin/env Rscript


#######################################################################################################################
# Set Working Directory
#######################################################################################################################

setwd("/home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/08_02_input_pvalued_without_iteration")

#######################################################################################################################
# Import data
#######################################################################################################################

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_000000001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_000000001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_000000001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_000000001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_000000001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_000000001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsGambier$RedVsGreen)
head(commun)
str(commun)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSKatiuVsGambier.txt")
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSKatiuVsHatchery.txt")
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSellowVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_HatcheryVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSKatiuVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_KatiuVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_RedVsGreenVSakapotoVsGambier$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_RedVsGreenVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_RedVsGreenVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_RedVsGreenVSYellowVsGreen$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_RedVsGreenVSYellowVsRed$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsGambierVSakapotoVsHatchery$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsHatcheryVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsKatiuVSellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_TakapotoVsKatiuVSellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000000001_YellowVsGreenVSellowVsRed$RedVsGreen.txt")
print(paste0("YellowVsGreen, YellowVsRed	:", res))

HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_000001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_000001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_000001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_000001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_000001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_000001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSKatiuVsGambier.txt")
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSKatiuVsHatchery.txt")
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSellowVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_HatcheryVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSKatiuVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_KatiuVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_RedVsGreenVSakapotoVsGambier$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_RedVsGreenVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_RedVsGreenVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_RedVsGreenVSYellowVsGreen$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_RedVsGreenVSYellowVsRed$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsGambierVSakapotoVsHatchery$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsHatcheryVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsKatiuVSellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_TakapotoVsKatiuVSellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_000001_YellowVsGreenVSellowVsRed$RedVsGreen.txt")
print(paste0("YellowVsGreen, YellowVsRed	:", res))


HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_001.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_001.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_001.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_001.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_001.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_001")
print("#######################################################")

commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSKatiuVsGambier.txt")
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSKatiuVsHatchery.txt")
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSellowVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_HatcheryVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSKatiuVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_KatiuVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_RedVsGreenVSakapotoVsGambier$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_RedVsGreenVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_RedVsGreenVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_RedVsGreenVSYellowVsGreen$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_RedVsGreenVSYellowVsRed$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsGambierVSakapotoVsHatchery$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsHatcheryVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsKatiuVSellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_TakapotoVsKatiuVSellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_001_YellowVsGreenVSellowVsRed$RedVsGreen.txt")
print(paste0("YellowVsGreen, YellowVsRed	:", res))


HatcheryVsGambier<-read.table("HatcheryVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
KatiuVsGambier<-read.table("KatiuVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
KatiuVsHatchery<-read.table("KatiuVsHatchery_dat_P_0_01.txt_SNP3.txt", header=T)
RedVsGreen<-read.table("RedVsGreen_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsGambier<-read.table("TakapotoVsGambier_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsHatchery<-read.table("TakapotoVsHatchery_dat_P_0_01.txt_SNP3.txt", header=T)
TakapotoVsKatiu<-read.table("TakapotoVsKatiu_dat_P_0_01.txt_SNP3.txt", header=T)
YellowVsGreen<-read.table("YellowVsGreen_dat_P_0_01.txt_SNP3.txt", header=T)
YellowVsRed<-read.table("YellowVsRed_dat_P_0_01.txt_SNP3.txt", header=T)

print("#######################################################")
print("P_0_01")
print("#######################################################")

commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSKatiuVsGambier.txt")
print(paste0("HatcheryVsGambier, KatiuVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSKatiuVsHatchery.txt")
print(paste0("HatcheryVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, RedVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSellowVsGreen$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsGreen	:", res))
commun<-intersect(HatcheryVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_HatcheryVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("HatcheryVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, KatiuVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSKatiuVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, KatiuVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSRedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, RedVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsGreen	:", res))
commun<-intersect(KatiuVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsGambier, YellowVsRed	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, RedVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSedVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, RedVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSTakapotoVsGambier$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsGambier	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsHatchery	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSellowVsGreen$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsGreen	:", res))
commun<-intersect(KatiuVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_KatiuVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("KatiuVsHatchery, YellowVsRed	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsGambier$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_RedVsGreenVSakapotoVsGambier$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsGambier	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_RedVsGreenVSTakapotoVsHatchery$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsHatchery	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_RedVsGreenVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("RedVsGreen, TakapotoVsKatiu	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_RedVsGreenVSYellowVsGreen$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsGreen	:", res))
commun<-intersect(RedVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_RedVsGreenVSYellowVsRed$RedVsGreen.txt")
print(paste0("RedVsGreen, YellowVsRed	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsHatchery$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsGambierVSakapotoVsHatchery$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsHatchery	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsGambierVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsGambierVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsGambier$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsGambierVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsGambier, YellowVsRed	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, TakapotoVsKatiu$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsHatcheryVSTakapotoVsKatiu$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, TakapotoVsKatiu	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsHatcheryVSYellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsHatchery$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsHatcheryVSYellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsHatchery, YellowVsRed	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsGreen$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsKatiuVSellowVsGreen$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsGreen	:", res))
commun<-intersect(TakapotoVsKatiu$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_TakapotoVsKatiuVSellowVsRed$RedVsGreen.txt")
print(paste0("TakapotoVsKatiu, YellowVsRed	:", res))
commun<-intersect(YellowVsGreen$RedVsGreen, YellowVsRed$RedVsGreen)
res <- length(commun)
write.table(commun, file = "P_0_01_YellowVsGreenVSellowVsRed$RedVsGreen.txt")
print(paste0("YellowVsGreen, YellowVsRed	:", res))

