#!/usr/bin/env bash
#PBS -q sequentiel
#PBS -l ncpus=1
#PBS -l mem=60gb
#PBS -l walltime=24:00:00
cd /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/03_trimmed
. /appli/bioinfo/fastqc/latest/env.sh
fastqc /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/03_trimmed/HI.4499.008.NS_Adaptor_14.pool6GV_R2.paired.fastq.gz -o /home1/datawork/plstenge/Pearl_Oyster_Colour_Population_Genomics/04_fastqc_trimmed
